#!/usr/bin/env bash

# help
if [ -z "$1" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
then
  echo "opget v0.0.1"
  echo "Sean Omlor <somlor@eml.cc>"
  echo ""
  echo "Get password for 1Password item."
  echo ""
  echo "Usage:"
  echo "  opget [item]"
  echo ""
  echo "Arguments:"
  echo "  item    item name."
  echo ""
  echo "Options:"
  echo "  -h, --help   show this help."
  echo ""
  exit 0
fi

# require 1password cli
if ! [ -x "$(command -v op)" ];
then
  echo "error: opget relies on 'op' which is unavailable."
  echo "see: https://support.1password.com/command-line"
  exit 1
fi

ITEM=$1
op get item ${ITEM} \
  | jq -r '.details.fields[] 
           | select(.designation == "password")
	   | .value'

